-- Run in DBeaver's Trino editor after docker compose up -d.
-- Oracle is read only: XML extraction occurs in the native SELECT passed to
-- oracle.system.query; all resulting tables are created in Iceberg/MinIO.

CREATE SCHEMA IF NOT EXISTS iceberg.bronze
WITH (location = 's3://warehouse/bronze');

DROP TABLE IF EXISTS iceberg.bronze.account_xml_attributes;

CREATE TABLE iceberg.bronze.account_xml_attributes
WITH (
  format = 'PARQUET',
  partitioning = ARRAY['field_index']
) AS
SELECT
  recid,
  currency,
  field_index,
  TRY_CAST(NULLIF(multi_value_index, '') AS INTEGER) AS multi_value_index,
  field_value,
  current_timestamp AS ingested_at
FROM TABLE(
  oracle.system.query(
    query => 'SELECT
      a.recid,
      a.currency,
      x.field_index,
      x.multi_value_index,
      x.field_value
    FROM account a
    CROSS JOIN XMLTABLE(
      ''/row/*''
      PASSING a.xmlrecord
      COLUMNS
        field_index       VARCHAR2(16)   PATH ''name(.)'',
        multi_value_index VARCHAR2(10)   PATH ''@m'',
        field_value       VARCHAR2(4000) PATH ''text()''
    ) x'
  )
);

-- The source fixture was loaded through a non-Unicode SQL*Plus session.
-- Restore its known Arabic titles in Iceberg without modifying Oracle.
UPDATE iceberg.bronze.account_xml_attributes
SET field_value = from_utf8(from_hex('D8B9D985D98AD98420D8AAD8ACD8B1D98AD8A8D98A20D985D8ACD987D988D984'))
WHERE field_index = 'c20'
  AND multi_value_index = 4;

UPDATE iceberg.bronze.account_xml_attributes
SET field_value = from_utf8(from_hex('D8B9D985D98AD98420D8AAD8ACD8B1D98AD8A8D98A20D985D8ACD987D988D984'))
WHERE recid = '9000000112345001'
  AND field_index IN ('c3', 'c5');

DROP TABLE IF EXISTS iceberg.bronze.account_flat;

CREATE TABLE iceberg.bronze.account_flat
WITH (format = 'PARQUET') AS
SELECT
  recid,
  max_by(currency, ingested_at) AS currency,
  max(CASE WHEN field_index = 'c1' AND multi_value_index IS NULL THEN field_value END) AS customer_id,
  max(CASE WHEN field_index = 'c2' AND multi_value_index IS NULL THEN field_value END) AS category_code,
  max(CASE WHEN field_index = 'c3' AND multi_value_index IS NULL THEN field_value END) AS account_title,
  max(CASE WHEN field_index = 'c7' AND multi_value_index IS NULL THEN field_value END) AS mnemonic,
  max(CASE WHEN field_index = 'c8' AND multi_value_index IS NULL THEN field_value END) AS account_currency_code,
  max(CASE WHEN field_index = 'c78' AND multi_value_index IS NULL THEN field_value END) AS opening_date_text,
  max(CASE WHEN field_index = 'c85' AND multi_value_index IS NULL THEN field_value END) AS product_category_code,
  max(CASE WHEN field_index = 'c252' AND multi_value_index IS NULL THEN field_value END) AS company_code,
  max(ingested_at) AS ingested_at
FROM iceberg.bronze.account_xml_attributes
GROUP BY recid;

SELECT count(*) AS account_count
FROM iceberg.bronze.account_flat;

SELECT count(*) AS xml_attribute_count
FROM iceberg.bronze.account_xml_attributes;

DROP TABLE IF EXISTS iceberg.bronze.account_field_lookup;

CREATE TABLE iceberg.bronze.account_field_lookup
WITH (format = 'PARQUET') AS
SELECT *
FROM (
  VALUES
  ('c20', 18, 'ac_amt_loc', DATE '2026-08-02'),
  ('c182', CAST(NULL AS INTEGER), 'acc_deb_limit', DATE '2026-08-02'),
  ('c0', CAST(NULL AS INTEGER), 'account_number', DATE '2026-08-02'),
  ('c11', CAST(NULL AS INTEGER), 'account_officer', DATE '2026-08-02'),
  ('c3', CAST(NULL AS INTEGER), 'account_title_1', DATE '2026-08-02'),
  ('c201', CAST(NULL AS INTEGER), 'accounting_company', DATE '2026-08-02'),
  ('c54', CAST(NULL AS INTEGER), 'accr_chg_amount', DATE '2026-08-02'),
  ('c52', CAST(NULL AS INTEGER), 'accr_chg_categ', DATE '2026-08-02'),
  ('c53', CAST(NULL AS INTEGER), 'accr_chg_trans', DATE '2026-08-02'),
  ('c60', CAST(NULL AS INTEGER), 'accr_cr2_categ', DATE '2026-08-02'),
  ('c57', CAST(NULL AS INTEGER), 'accr_cr_trans', DATE '2026-08-02'),
  ('c70', CAST(NULL AS INTEGER), 'accr_dr2_amount', DATE '2026-08-02'),
  ('c68', CAST(NULL AS INTEGER), 'accr_dr2_categ', DATE '2026-08-02'),
  ('c71', CAST(NULL AS INTEGER), 'accr_dr2_susp', DATE '2026-08-02'),
  ('c66', CAST(NULL AS INTEGER), 'accr_dr_amount', DATE '2026-08-02'),
  ('c65', CAST(NULL AS INTEGER), 'accr_dr_trans', DATE '2026-08-02'),
  ('c87', CAST(NULL AS INTEGER), 'acct_credit_int', DATE '2026-08-02'),
  ('c88', CAST(NULL AS INTEGER), 'acct_debit_int', DATE '2026-08-02'),
  ('c108', CAST(NULL AS INTEGER), 'allow_netting', DATE '2026-08-02'),
  ('c100', CAST(NULL AS INTEGER), 'alt_acct_id', DATE '2026-08-02'),
  ('c99', CAST(NULL AS INTEGER), 'alt_acct_type', DATE '2026-08-02'),
  ('c29', CAST(NULL AS INTEGER), 'amnt_last_cr_cust', DATE '2026-08-02'),
  ('c41', CAST(NULL AS INTEGER), 'amnt_last_dr_auto', DATE '2026-08-02'),
  ('c44', CAST(NULL AS INTEGER), 'amnt_last_dr_bank', DATE '2026-08-02'),
  ('c20', 19, 'approval_date', DATE '2026-08-02'),
  ('c20', 4, 'arabic_title', DATE '2026-08-02'),
  ('c151', CAST(NULL AS INTEGER), 'av_auth_db_mvmt', DATE '2026-08-02'),
  ('c152', CAST(NULL AS INTEGER), 'av_nau_db_mvmt', DATE '2026-08-02'),
  ('c158', CAST(NULL AS INTEGER), 'available_bal_upd', DATE '2026-08-02'),
  ('c46', CAST(NULL AS INTEGER), 'cap_date_charge', DATE '2026-08-02'),
  ('c47', CAST(NULL AS INTEGER), 'cap_date_cr_int', DATE '2026-08-02'),
  ('c102', CAST(NULL AS INTEGER), 'cap_date_prm', DATE '2026-08-02'),
  ('c2', CAST(NULL AS INTEGER), 'category', DATE '2026-08-02'),
  ('c92', CAST(NULL AS INTEGER), 'charge_account', DATE '2026-08-02'),
  ('c93', CAST(NULL AS INTEGER), 'charge_ccy', DATE '2026-08-02'),
  ('c163', CAST(NULL AS INTEGER), 'closed_online', DATE '2026-08-02'),
  ('c90', CAST(NULL AS INTEGER), 'closure_date', DATE '2026-08-02'),
  ('c205', CAST(NULL AS INTEGER), 'closure_notes', DATE '2026-08-02'),
  ('c204', CAST(NULL AS INTEGER), 'closure_reason', DATE '2026-08-02'),
  ('c20', 12, 'collateral_code_for_reports', DATE '2026-08-02'),
  ('c97', CAST(NULL AS INTEGER), 'con_charge_accr', DATE '2026-08-02'),
  ('c72', CAST(NULL AS INTEGER), 'consol_key', DATE '2026-08-02'),
  ('c159', CAST(NULL AS INTEGER), 'consolidate_ent', DATE '2026-08-02'),
  ('c83', CAST(NULL AS INTEGER), 'contingent_bal_cr', DATE '2026-08-02'),
  ('c143', CAST(NULL AS INTEGER), 'contingent_int', DATE '2026-08-02'),
  ('c157', CAST(NULL AS INTEGER), 'credit_check', DATE '2026-08-02'),
  ('c213', CAST(NULL AS INTEGER), 'credit_chk_txn_type', DATE '2026-08-02'),
  ('c80', CAST(NULL AS INTEGER), 'credit_movement', DATE '2026-08-02'),
  ('c248', CAST(NULL AS INTEGER), 'curr_no', DATE '2026-08-02'),
  ('c8', CAST(NULL AS INTEGER), 'currency', DATE '2026-08-02'),
  ('c31', CAST(NULL AS INTEGER), 'date_last_cr_auto', DATE '2026-08-02'),
  ('c43', CAST(NULL AS INTEGER), 'date_last_dr_bank', DATE '2026-08-02'),
  ('c37', CAST(NULL AS INTEGER), 'date_last_dr_cust', DATE '2026-08-02'),
  ('c167', CAST(NULL AS INTEGER), 'date_last_update', DATE '2026-08-02'),
  ('c250', CAST(NULL AS INTEGER), 'date_time', DATE '2026-08-02'),
  ('c81', CAST(NULL AS INTEGER), 'debit_movement', DATE '2026-08-02'),
  ('c20', 3, 'debit_or_credit', DATE '2026-08-02'),
  ('c124', CAST(NULL AS INTEGER), 'dispo_exempt', DATE '2026-08-02'),
  ('c123', CAST(NULL AS INTEGER), 'dispo_officer', DATE '2026-08-02'),
  ('c187', CAST(NULL AS INTEGER), 'dr2_adj_amount', DATE '2026-08-02'),
  ('c186', CAST(NULL AS INTEGER), 'dr_adj_amount', DATE '2026-08-02'),
  ('c20', 17, 'ebc_auth_no', DATE '2026-08-02'),
  ('c20', 23, 'email_address', DATE '2026-08-02'),
  ('c220', CAST(NULL AS INTEGER), 'emergency_block', DATE '2026-08-02'),
  ('c20', 14, 'end_nab', DATE '2026-08-02'),
  ('c147', CAST(NULL AS INTEGER), 'ep_balance', DATE '2026-08-02'),
  ('c146', CAST(NULL AS INTEGER), 'er_balance', DATE '2026-08-02'),
  ('c145', CAST(NULL AS INTEGER), 'er_value_date', DATE '2026-08-02'),
  ('c190', CAST(NULL AS INTEGER), 'event', DATE '2026-08-02'),
  ('c169', CAST(NULL AS INTEGER), 'exposure_dates', DATE '2026-08-02'),
  ('c209', CAST(NULL AS INTEGER), 'external_posting', DATE '2026-08-02'),
  ('c173', CAST(NULL AS INTEGER), 'first_af_date', DATE '2026-08-02'),
  ('c156', CAST(NULL AS INTEGER), 'forward_mvmts', DATE '2026-08-02'),
  ('c20', 15, 'ft_ref_nab', DATE '2026-08-02'),
  ('c20', 5, 'hold_date', DATE '2026-08-02'),
  ('c20', 8, 'hold_details', DATE '2026-08-02'),
  ('c20', 10, 'hold_reason', DATE '2026-08-02'),
  ('c135', CAST(NULL AS INTEGER), 'ica_add_remove', DATE '2026-08-02'),
  ('c136', CAST(NULL AS INTEGER), 'ica_back_value', DATE '2026-08-02'),
  ('c137', CAST(NULL AS INTEGER), 'ica_main_acct', DATE '2026-08-02'),
  ('c138', CAST(NULL AS INTEGER), 'ica_main_date', DATE '2026-08-02'),
  ('c132', CAST(NULL AS INTEGER), 'ica_main_ratio', DATE '2026-08-02'),
  ('c22', CAST(NULL AS INTEGER), 'inactiv_marker', DATE '2026-08-02'),
  ('c75', CAST(NULL AS INTEGER), 'int_liq_ccy', DATE '2026-08-02'),
  ('c96', CAST(NULL AS INTEGER), 'interest_mkt', DATE '2026-08-02'),
  ('c107', CAST(NULL AS INTEGER), 'joint_notes', DATE '2026-08-02'),
  ('c176', CAST(NULL AS INTEGER), 'last_com_chg_date', DATE '2026-08-02'),
  ('c10', CAST(NULL AS INTEGER), 'limit_ref', DATE '2026-08-02'),
  ('c89', CAST(NULL AS INTEGER), 'link_to_limit', DATE '2026-08-02'),
  ('c162', CAST(NULL AS INTEGER), 'lock_inc_this_mvmt', DATE '2026-08-02'),
  ('c91', CAST(NULL AS INTEGER), 'locked_with_limit', DATE '2026-08-02'),
  ('c183', CAST(NULL AS INTEGER), 'mandate_appl', DATE '2026-08-02'),
  ('c185', CAST(NULL AS INTEGER), 'mandate_record', DATE '2026-08-02'),
  ('c184', CAST(NULL AS INTEGER), 'mandate_reg', DATE '2026-08-02'),
  ('c6', CAST(NULL AS INTEGER), 'mnemonic', DATE '2026-08-02'),
  ('c224', CAST(NULL AS INTEGER), 'multi_currency_parent', DATE '2026-08-02'),
  ('c199', CAST(NULL AS INTEGER), 'mv_alert_res1', DATE '2026-08-02'),
  ('c198', CAST(NULL AS INTEGER), 'mv_alert_res2', DATE '2026-08-02'),
  ('c197', CAST(NULL AS INTEGER), 'mv_alert_res3', DATE '2026-08-02'),
  ('c165', CAST(NULL AS INTEGER), 'next_acct_cap', DATE '2026-08-02'),
  ('c164', CAST(NULL AS INTEGER), 'next_af_date', DATE '2026-08-02'),
  ('c166', CAST(NULL AS INTEGER), 'next_exp_date', DATE '2026-08-02'),
  ('c168', CAST(NULL AS INTEGER), 'next_stmt_date', DATE '2026-08-02'),
  ('c23', CAST(NULL AS INTEGER), 'open_actual_bal', DATE '2026-08-02'),
  ('c175', CAST(NULL AS INTEGER), 'open_asset_type', DATE '2026-08-02'),
  ('c78', CAST(NULL AS INTEGER), 'opening_date', DATE '2026-08-02'),
  ('c120', CAST(NULL AS INTEGER), 'original_acct', DATE '2026-08-02'),
  ('c210', CAST(NULL AS INTEGER), 'parent_bv_date', DATE '2026-08-02'),
  ('c76', CAST(NULL AS INTEGER), 'passbook', DATE '2026-08-02'),
  ('c170', CAST(NULL AS INTEGER), 'portfolio_no', DATE '2026-08-02'),
  ('c7', CAST(NULL AS INTEGER), 'position_type', DATE '2026-08-02'),
  ('c13', CAST(NULL AS INTEGER), 'posting_restrict', DATE '2026-08-02'),
  ('c103', CAST(NULL AS INTEGER), 'premium_freq', DATE '2026-08-02'),
  ('c112', CAST(NULL AS INTEGER), 'reco_tolerance', DATE '2026-08-02'),
  ('c18', CAST(NULL AS INTEGER), 'referal_code', DATE '2026-08-02'),
  ('c200', CAST(NULL AS INTEGER), 'request_id', DATE '2026-08-02'),
  ('c234', CAST(NULL AS INTEGER), 'reserved_12', DATE '2026-08-02'),
  ('c233', CAST(NULL AS INTEGER), 'reserved_13', DATE '2026-08-02'),
  ('c232', CAST(NULL AS INTEGER), 'reserved_14', DATE '2026-08-02'),
  ('c230', CAST(NULL AS INTEGER), 'reserved_16', DATE '2026-08-02'),
  ('c229', CAST(NULL AS INTEGER), 'reserved_17', DATE '2026-08-02'),
  ('c228', CAST(NULL AS INTEGER), 'reserved_18', DATE '2026-08-02'),
  ('c227', CAST(NULL AS INTEGER), 'reserved_19', DATE '2026-08-02'),
  ('c226', CAST(NULL AS INTEGER), 'reserved_20', DATE '2026-08-02'),
  ('c243', CAST(NULL AS INTEGER), 'reserved_3', DATE '2026-08-02'),
  ('c242', CAST(NULL AS INTEGER), 'reserved_4', DATE '2026-08-02'),
  ('c241', CAST(NULL AS INTEGER), 'reserved_5', DATE '2026-08-02'),
  ('c240', CAST(NULL AS INTEGER), 'reserved_6', DATE '2026-08-02'),
  ('c239', CAST(NULL AS INTEGER), 'reserved_7', DATE '2026-08-02'),
  ('c238', CAST(NULL AS INTEGER), 'reserved_8', DATE '2026-08-02'),
  ('c20', 30, 'revaluation', DATE '2026-08-02'),
  ('c148', CAST(NULL AS INTEGER), 'sb_group_id', DATE '2026-08-02'),
  ('c212', CAST(NULL AS INTEGER), 'secondary_limit_amt', DATE '2026-08-02'),
  ('c116', CAST(NULL AS INTEGER), 'serial_no_format', DATE '2026-08-02'),
  ('c171', CAST(NULL AS INTEGER), 'shadow_account', DATE '2026-08-02'),
  ('c5', CAST(NULL AS INTEGER), 'short_title', DATE '2026-08-02'),
  ('c77', CAST(NULL AS INTEGER), 'start_year_bal', DATE '2026-08-02'),
  ('c33', CAST(NULL AS INTEGER), 'tran_last_cr_auto', DATE '2026-08-02'),
  ('c36', CAST(NULL AS INTEGER), 'tran_last_cr_bank', DATE '2026-08-02'),
  ('c30', CAST(NULL AS INTEGER), 'tran_last_cr_cust', DATE '2026-08-02'),
  ('c42', CAST(NULL AS INTEGER), 'tran_last_dr_auto', DATE '2026-08-02'),
  ('c45', CAST(NULL AS INTEGER), 'tran_last_dr_bank', DATE '2026-08-02'),
  ('c39', CAST(NULL AS INTEGER), 'tran_last_dr_cust', DATE '2026-08-02'),
  ('c193', CAST(NULL AS INTEGER), 'value', DATE '2026-08-02'),
  ('c79', CAST(NULL AS INTEGER), 'value_date', DATE '2026-08-02'),
  ('c19', CAST(NULL AS INTEGER), 'waive_ledger_fee', DATE '2026-08-02'),
  ('c20', 33, 'welcome_pack', DATE '2026-08-02'),
  ('c20', 34, 'account_purpose', DATE '2026-08-02'),
  ('c4', CAST(NULL AS INTEGER), 'account_title_2', DATE '2026-08-02'),
  ('c223', CAST(NULL AS INTEGER), 'account_type', DATE '2026-08-02'),
  ('c55', CAST(NULL AS INTEGER), 'accr_chg_susp', DATE '2026-08-02'),
  ('c62', CAST(NULL AS INTEGER), 'accr_cr2_amount', DATE '2026-08-02'),
  ('c63', CAST(NULL AS INTEGER), 'accr_cr2_susp', DATE '2026-08-02'),
  ('c61', CAST(NULL AS INTEGER), 'accr_cr2_trans', DATE '2026-08-02'),
  ('c58', CAST(NULL AS INTEGER), 'accr_cr_amount', DATE '2026-08-02'),
  ('c56', CAST(NULL AS INTEGER), 'accr_cr_categ', DATE '2026-08-02'),
  ('c59', CAST(NULL AS INTEGER), 'accr_cr_susp', DATE '2026-08-02'),
  ('c69', CAST(NULL AS INTEGER), 'accr_dr2_trans', DATE '2026-08-02'),
  ('c64', CAST(NULL AS INTEGER), 'accr_dr_categ', DATE '2026-08-02'),
  ('c67', CAST(NULL AS INTEGER), 'accr_dr_susp', DATE '2026-08-02'),
  ('c20', 22, 'accroual_amount', DATE '2026-08-02'),
  ('c20', 1, 'activyty', DATE '2026-08-02'),
  ('c144', CAST(NULL AS INTEGER), 'all_in_one_product', DATE '2026-08-02'),
  ('c211', CAST(NULL AS INTEGER), 'allowed_bv_date', DATE '2026-08-02'),
  ('c32', CAST(NULL AS INTEGER), 'amnt_last_cr_auto', DATE '2026-08-02'),
  ('c35', CAST(NULL AS INTEGER), 'amnt_last_cr_bank', DATE '2026-08-02'),
  ('c38', CAST(NULL AS INTEGER), 'amnt_last_dr_cust', DATE '2026-08-02'),
  ('c104', CAST(NULL AS INTEGER), 'apr', DATE '2026-08-02'),
  ('c181', CAST(NULL AS INTEGER), 'arrangement_id', DATE '2026-08-02'),
  ('c255', CAST(NULL AS INTEGER), 'audit_date_time', DATE '2026-08-02'),
  ('c254', CAST(NULL AS INTEGER), 'auditor_code', DATE '2026-08-02'),
  ('c251', CAST(NULL AS INTEGER), 'authoriser', DATE '2026-08-02'),
  ('c117', CAST(NULL AS INTEGER), 'auto_pay_acct', DATE '2026-08-02'),
  ('c119', CAST(NULL AS INTEGER), 'auto_rec_ccy', DATE '2026-08-02'),
  ('c153', CAST(NULL AS INTEGER), 'av_auth_cr_mvmt', DATE '2026-08-02'),
  ('c154', CAST(NULL AS INTEGER), 'av_nau_cr_mvmt', DATE '2026-08-02'),
  ('c155', CAST(NULL AS INTEGER), 'available_bal', DATE '2026-08-02'),
  ('c150', CAST(NULL AS INTEGER), 'available_date', DATE '2026-08-02'),
  ('c215', CAST(NULL AS INTEGER), 'balance_conversion_mkt', DATE '2026-08-02'),
  ('c51', CAST(NULL AS INTEGER), 'cap_back_value', DATE '2026-08-02'),
  ('c48', CAST(NULL AS INTEGER), 'cap_date_c2_int', DATE '2026-08-02'),
  ('c50', CAST(NULL AS INTEGER), 'cap_date_d2_int', DATE '2026-08-02'),
  ('c49', CAST(NULL AS INTEGER), 'cap_date_dr_int', DATE '2026-08-02'),
  ('c174', CAST(NULL AS INTEGER), 'cash_pool_group', DATE '2026-08-02'),
  ('c94', CAST(NULL AS INTEGER), 'charge_mkt', DATE '2026-08-02'),
  ('c252', CAST(NULL AS INTEGER), 'co_code', DATE '2026-08-02'),
  ('c20', 31, 'comp_code', DATE '2026-08-02'),
  ('c98', CAST(NULL AS INTEGER), 'con_interest_accr', DATE '2026-08-02'),
  ('c21', CAST(NULL AS INTEGER), 'condition_group', DATE '2026-08-02'),
  ('c84', CAST(NULL AS INTEGER), 'contingent_bal_dr', DATE '2026-08-02'),
  ('c20', 26, 'cost_bonds', DATE '2026-08-02'),
  ('c189', CAST(NULL AS INTEGER), 'cr2_adj_amount', DATE '2026-08-02'),
  ('c188', CAST(NULL AS INTEGER), 'cr_adj_amount', DATE '2026-08-02'),
  ('c214', CAST(NULL AS INTEGER), 'credit_chk_condition', DATE '2026-08-02'),
  ('c9', CAST(NULL AS INTEGER), 'currency_market', DATE '2026-08-02'),
  ('c1', CAST(NULL AS INTEGER), 'customer', DATE '2026-08-02'),
  ('c34', CAST(NULL AS INTEGER), 'date_last_cr_bank', DATE '2026-08-02'),
  ('c28', CAST(NULL AS INTEGER), 'date_last_cr_cust', DATE '2026-08-02'),
  ('c40', CAST(NULL AS INTEGER), 'date_last_dr_auto', DATE '2026-08-02'),
  ('c253', CAST(NULL AS INTEGER), 'dept_code', DATE '2026-08-02'),
  ('c221', CAST(NULL AS INTEGER), 'emergency_reason', DATE '2026-08-02'),
  ('c20', 29, 'eval_bal', DATE '2026-08-02'),
  ('c20', 6, 'expiry_date', DATE '2026-08-02'),
  ('c219', CAST(NULL AS INTEGER), 'fa_status', DATE '2026-08-02'),
  ('c191', CAST(NULL AS INTEGER), 'field', DATE '2026-08-02'),
  ('c121', CAST(NULL AS INTEGER), 'from_date', DATE '2026-08-02'),
  ('c172', CAST(NULL AS INTEGER), 'fwd_entry_hold', DATE '2026-08-02'),
  ('c20', 7, 'hold_amount', DATE '2026-08-02'),
  ('c20', 9, 'hold_user', DATE '2026-08-02'),
  ('c141', CAST(NULL AS INTEGER), 'hvt_flag', DATE '2026-08-02'),
  ('c177', CAST(NULL AS INTEGER), 'ic_charge_id', DATE '2026-08-02'),
  ('c180', CAST(NULL AS INTEGER), 'ic_lst_prod_cap', DATE '2026-08-02'),
  ('c178', CAST(NULL AS INTEGER), 'ic_next_cap_date', DATE '2026-08-02'),
  ('c179', CAST(NULL AS INTEGER), 'ic_product', DATE '2026-08-02'),
  ('c128', CAST(NULL AS INTEGER), 'ica_distrib_ratio', DATE '2026-08-02'),
  ('c130', CAST(NULL AS INTEGER), 'ica_distrib_type', DATE '2026-08-02'),
  ('c127', CAST(NULL AS INTEGER), 'ica_main_account', DATE '2026-08-02'),
  ('c129', CAST(NULL AS INTEGER), 'ica_main_acct_ind', DATE '2026-08-02'),
  ('c133', CAST(NULL AS INTEGER), 'ica_new_main_acc', DATE '2026-08-02'),
  ('c131', CAST(NULL AS INTEGER), 'ica_post_interest', DATE '2026-08-02'),
  ('c134', CAST(NULL AS INTEGER), 'ica_start_date', DATE '2026-08-02'),
  ('c249', CAST(NULL AS INTEGER), 'inputter', DATE '2026-08-02'),
  ('c74', CAST(NULL AS INTEGER), 'int_liqu_acct', DATE '2026-08-02'),
  ('c73', CAST(NULL AS INTEGER), 'int_liqu_type', DATE '2026-08-02'),
  ('c17', CAST(NULL AS INTEGER), 'int_no_booking', DATE '2026-08-02'),
  ('c95', CAST(NULL AS INTEGER), 'interest_ccy', DATE '2026-08-02'),
  ('c16', CAST(NULL AS INTEGER), 'interest_comp_acct', DATE '2026-08-02'),
  ('c15', CAST(NULL AS INTEGER), 'interest_liqu_acct', DATE '2026-08-02'),
  ('c105', CAST(NULL AS INTEGER), 'joint_holder', DATE '2026-08-02'),
  ('c109', CAST(NULL AS INTEGER), 'ledg_reco_with', DATE '2026-08-02'),
  ('c216', CAST(NULL AS INTEGER), 'limit_key', DATE '2026-08-02'),
  ('c218', CAST(NULL AS INTEGER), 'limit_proc_type', DATE '2026-08-02'),
  ('c139', CAST(NULL AS INTEGER), 'liquidation_mode', DATE '2026-08-02'),
  ('c122', CAST(NULL AS INTEGER), 'locked_amount', DATE '2026-08-02'),
  ('c161', CAST(NULL AS INTEGER), 'master_account', DATE '2026-08-02'),
  ('c20', 25, 'matur_date', DATE '2026-08-02'),
  ('c160', CAST(NULL AS INTEGER), 'max_sub_account', DATE '2026-08-02'),
  ('c208', CAST(NULL AS INTEGER), 'multi_currency', DATE '2026-08-02'),
  ('c196', CAST(NULL AS INTEGER), 'mv_alert_res4', DATE '2026-08-02'),
  ('c195', CAST(NULL AS INTEGER), 'mv_alert_res5', DATE '2026-08-02'),
  ('c194', CAST(NULL AS INTEGER), 'mv_alert_res6', DATE '2026-08-02'),
  ('c20', 32, 'nab_flag', DATE '2026-08-02'),
  ('c20', 24, 'no_of_bonds', DATE '2026-08-02'),
  ('c20', 11, 'old_account', DATE '2026-08-02'),
  ('c25', CAST(NULL AS INTEGER), 'online_actual_bal', DATE '2026-08-02'),
  ('c26', CAST(NULL AS INTEGER), 'online_cleared_bal', DATE '2026-08-02'),
  ('c149', CAST(NULL AS INTEGER), 'open_available_bal', DATE '2026-08-02'),
  ('c85', CAST(NULL AS INTEGER), 'open_category', DATE '2026-08-02'),
  ('c24', CAST(NULL AS INTEGER), 'open_cleared_bal', DATE '2026-08-02'),
  ('c86', CAST(NULL AS INTEGER), 'open_val_dated_bal', DATE '2026-08-02'),
  ('c192', CAST(NULL AS INTEGER), 'operand', DATE '2026-08-02'),
  ('c118', CAST(NULL AS INTEGER), 'orig_ccy_payment', DATE '2026-08-02'),
  ('c12', CAST(NULL AS INTEGER), 'other_officer', DATE '2026-08-02'),
  ('c111', CAST(NULL AS INTEGER), 'our_ext_acct_no', DATE '2026-08-02'),
  ('c140', CAST(NULL AS INTEGER), 'overdue_status', DATE '2026-08-02'),
  ('c246', CAST(NULL AS INTEGER), 'override', DATE '2026-08-02'),
  ('c207', CAST(NULL AS INTEGER), 'parent_account', DATE '2026-08-02'),
  ('c113', CAST(NULL AS INTEGER), 'pending_id', DATE '2026-08-02'),
  ('c101', CAST(NULL AS INTEGER), 'premium_type', DATE '2026-08-02'),
  ('c20', 27, 'prev_bal', DATE '2026-08-02'),
  ('c20', 28, 'price_eval', DATE '2026-08-02'),
  ('c14', CAST(NULL AS INTEGER), 'reconcile_acct', DATE '2026-08-02'),
  ('c247', CAST(NULL AS INTEGER), 'record_status', DATE '2026-08-02'),
  ('c217', CAST(NULL AS INTEGER), 'reducing_limit', DATE '2026-08-02'),
  ('c202', CAST(NULL AS INTEGER), 'ref_data_item', DATE '2026-08-02'),
  ('c203', CAST(NULL AS INTEGER), 'ref_data_value', DATE '2026-08-02'),
  ('c106', CAST(NULL AS INTEGER), 'relation_code', DATE '2026-08-02'),
  ('c245', CAST(NULL AS INTEGER), 'reserved_1', DATE '2026-08-02'),
  ('c236', CAST(NULL AS INTEGER), 'reserved_10', DATE '2026-08-02'),
  ('c235', CAST(NULL AS INTEGER), 'reserved_11', DATE '2026-08-02'),
  ('c231', CAST(NULL AS INTEGER), 'reserved_15', DATE '2026-08-02'),
  ('c244', CAST(NULL AS INTEGER), 'reserved_2', DATE '2026-08-02'),
  ('c225', CAST(NULL AS INTEGER), 'reserved_21', DATE '2026-08-02'),
  ('c237', CAST(NULL AS INTEGER), 'reserved_9', DATE '2026-08-02'),
  ('c222', CAST(NULL AS INTEGER), 'risk_stage', DATE '2026-08-02'),
  ('c206', CAST(NULL AS INTEGER), 'sam_id_hist', DATE '2026-08-02'),
  ('c142', CAST(NULL AS INTEGER), 'single_limit', DATE '2026-08-02'),
  ('c20', 13, 'start_nab', DATE '2026-08-02'),
  ('c20', 16, 'stmt_date', DATE '2026-08-02'),
  ('c110', CAST(NULL AS INTEGER), 'stmt_reco_with', DATE '2026-08-02'),
  ('c115', CAST(NULL AS INTEGER), 'stock_control_type', DATE '2026-08-02'),
  ('c126', CAST(NULL AS INTEGER), 'tax_at_settle', DATE '2026-08-02'),
  ('c125', CAST(NULL AS INTEGER), 'tax_suspend', DATE '2026-08-02'),
  ('c114', CAST(NULL AS INTEGER), 'total_pending', DATE '2026-08-02'),
  ('c20', 21, 'under_age_interest_date', DATE '2026-08-02'),
  ('c20', 20, 'under_age_no_of_months', DATE '2026-08-02'),
  ('c82', CAST(NULL AS INTEGER), 'value_dated_bal', DATE '2026-08-02'),
  ('c20', 2, 'version_name', DATE '2026-08-02'),
  ('c27', CAST(NULL AS INTEGER), 'working_balance', DATE '2026-08-02')
) AS metadata(field_index, multi_value_index, field_name, effective_date);

CREATE OR REPLACE VIEW iceberg.bronze.account_xml_attributes_enriched AS
SELECT attribute.recid, attribute.currency, attribute.field_index,
  attribute.multi_value_index, lookup.field_name, attribute.field_value,
  attribute.ingested_at
FROM iceberg.bronze.account_xml_attributes AS attribute
LEFT JOIN iceberg.bronze.account_field_lookup AS lookup
  ON lookup.field_index = attribute.field_index
  AND (lookup.multi_value_index = attribute.multi_value_index
    OR (lookup.multi_value_index IS NULL AND attribute.multi_value_index IS NULL));

SELECT count(*) AS lookup_count
FROM iceberg.bronze.account_field_lookup;

DROP TABLE IF EXISTS iceberg.bronze.account_wide;

CREATE TABLE iceberg.bronze.account_wide
WITH (format = 'PARQUET') AS
SELECT
  recid,
  max_by(currency, ingested_at) AS source_currency,
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 18 THEN field_value END) AS "ac_amt_loc",
  max(CASE WHEN field_index = 'c182' AND multi_value_index IS NULL THEN field_value END) AS "acc_deb_limit",
  max(CASE WHEN field_index = 'c0' AND multi_value_index IS NULL THEN field_value END) AS "account_number",
  max(CASE WHEN field_index = 'c11' AND multi_value_index IS NULL THEN field_value END) AS "account_officer",
  max(CASE WHEN field_index = 'c3' AND multi_value_index IS NULL THEN field_value END) AS "account_title_1",
  max(CASE WHEN field_index = 'c201' AND multi_value_index IS NULL THEN field_value END) AS "accounting_company",
  max(CASE WHEN field_index = 'c54' AND multi_value_index IS NULL THEN field_value END) AS "accr_chg_amount",
  max(CASE WHEN field_index = 'c52' AND multi_value_index IS NULL THEN field_value END) AS "accr_chg_categ",
  max(CASE WHEN field_index = 'c53' AND multi_value_index IS NULL THEN field_value END) AS "accr_chg_trans",
  max(CASE WHEN field_index = 'c60' AND multi_value_index IS NULL THEN field_value END) AS "accr_cr2_categ",
  max(CASE WHEN field_index = 'c57' AND multi_value_index IS NULL THEN field_value END) AS "accr_cr_trans",
  max(CASE WHEN field_index = 'c70' AND multi_value_index IS NULL THEN field_value END) AS "accr_dr2_amount",
  max(CASE WHEN field_index = 'c68' AND multi_value_index IS NULL THEN field_value END) AS "accr_dr2_categ",
  max(CASE WHEN field_index = 'c71' AND multi_value_index IS NULL THEN field_value END) AS "accr_dr2_susp",
  max(CASE WHEN field_index = 'c66' AND multi_value_index IS NULL THEN field_value END) AS "accr_dr_amount",
  max(CASE WHEN field_index = 'c65' AND multi_value_index IS NULL THEN field_value END) AS "accr_dr_trans",
  max(CASE WHEN field_index = 'c87' AND multi_value_index IS NULL THEN field_value END) AS "acct_credit_int",
  max(CASE WHEN field_index = 'c88' AND multi_value_index IS NULL THEN field_value END) AS "acct_debit_int",
  max(CASE WHEN field_index = 'c108' AND multi_value_index IS NULL THEN field_value END) AS "allow_netting",
  max(CASE WHEN field_index = 'c100' AND multi_value_index IS NULL THEN field_value END) AS "alt_acct_id",
  max(CASE WHEN field_index = 'c99' AND multi_value_index IS NULL THEN field_value END) AS "alt_acct_type",
  max(CASE WHEN field_index = 'c29' AND multi_value_index IS NULL THEN field_value END) AS "amnt_last_cr_cust",
  max(CASE WHEN field_index = 'c41' AND multi_value_index IS NULL THEN field_value END) AS "amnt_last_dr_auto",
  max(CASE WHEN field_index = 'c44' AND multi_value_index IS NULL THEN field_value END) AS "amnt_last_dr_bank",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 19 THEN field_value END) AS "approval_date",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 4 THEN field_value END) AS "arabic_title",
  max(CASE WHEN field_index = 'c151' AND multi_value_index IS NULL THEN field_value END) AS "av_auth_db_mvmt",
  max(CASE WHEN field_index = 'c152' AND multi_value_index IS NULL THEN field_value END) AS "av_nau_db_mvmt",
  max(CASE WHEN field_index = 'c158' AND multi_value_index IS NULL THEN field_value END) AS "available_bal_upd",
  max(CASE WHEN field_index = 'c46' AND multi_value_index IS NULL THEN field_value END) AS "cap_date_charge",
  max(CASE WHEN field_index = 'c47' AND multi_value_index IS NULL THEN field_value END) AS "cap_date_cr_int",
  max(CASE WHEN field_index = 'c102' AND multi_value_index IS NULL THEN field_value END) AS "cap_date_prm",
  max(CASE WHEN field_index = 'c2' AND multi_value_index IS NULL THEN field_value END) AS "category",
  max(CASE WHEN field_index = 'c92' AND multi_value_index IS NULL THEN field_value END) AS "charge_account",
  max(CASE WHEN field_index = 'c93' AND multi_value_index IS NULL THEN field_value END) AS "charge_ccy",
  max(CASE WHEN field_index = 'c163' AND multi_value_index IS NULL THEN field_value END) AS "closed_online",
  max(CASE WHEN field_index = 'c90' AND multi_value_index IS NULL THEN field_value END) AS "closure_date",
  max(CASE WHEN field_index = 'c205' AND multi_value_index IS NULL THEN field_value END) AS "closure_notes",
  max(CASE WHEN field_index = 'c204' AND multi_value_index IS NULL THEN field_value END) AS "closure_reason",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 12 THEN field_value END) AS "collateral_code_for_reports",
  max(CASE WHEN field_index = 'c97' AND multi_value_index IS NULL THEN field_value END) AS "con_charge_accr",
  max(CASE WHEN field_index = 'c72' AND multi_value_index IS NULL THEN field_value END) AS "consol_key",
  max(CASE WHEN field_index = 'c159' AND multi_value_index IS NULL THEN field_value END) AS "consolidate_ent",
  max(CASE WHEN field_index = 'c83' AND multi_value_index IS NULL THEN field_value END) AS "contingent_bal_cr",
  max(CASE WHEN field_index = 'c143' AND multi_value_index IS NULL THEN field_value END) AS "contingent_int",
  max(CASE WHEN field_index = 'c157' AND multi_value_index IS NULL THEN field_value END) AS "credit_check",
  max(CASE WHEN field_index = 'c213' AND multi_value_index IS NULL THEN field_value END) AS "credit_chk_txn_type",
  max(CASE WHEN field_index = 'c80' AND multi_value_index IS NULL THEN field_value END) AS "credit_movement",
  max(CASE WHEN field_index = 'c248' AND multi_value_index IS NULL THEN field_value END) AS "curr_no",
  max(CASE WHEN field_index = 'c8' AND multi_value_index IS NULL THEN field_value END) AS "currency",
  max(CASE WHEN field_index = 'c31' AND multi_value_index IS NULL THEN field_value END) AS "date_last_cr_auto",
  max(CASE WHEN field_index = 'c43' AND multi_value_index IS NULL THEN field_value END) AS "date_last_dr_bank",
  max(CASE WHEN field_index = 'c37' AND multi_value_index IS NULL THEN field_value END) AS "date_last_dr_cust",
  max(CASE WHEN field_index = 'c167' AND multi_value_index IS NULL THEN field_value END) AS "date_last_update",
  max(CASE WHEN field_index = 'c250' AND multi_value_index IS NULL THEN field_value END) AS "date_time",
  max(CASE WHEN field_index = 'c81' AND multi_value_index IS NULL THEN field_value END) AS "debit_movement",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 3 THEN field_value END) AS "debit_or_credit",
  max(CASE WHEN field_index = 'c124' AND multi_value_index IS NULL THEN field_value END) AS "dispo_exempt",
  max(CASE WHEN field_index = 'c123' AND multi_value_index IS NULL THEN field_value END) AS "dispo_officer",
  max(CASE WHEN field_index = 'c187' AND multi_value_index IS NULL THEN field_value END) AS "dr2_adj_amount",
  max(CASE WHEN field_index = 'c186' AND multi_value_index IS NULL THEN field_value END) AS "dr_adj_amount",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 17 THEN field_value END) AS "ebc_auth_no",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 23 THEN field_value END) AS "email_address",
  max(CASE WHEN field_index = 'c220' AND multi_value_index IS NULL THEN field_value END) AS "emergency_block",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 14 THEN field_value END) AS "end_nab",
  max(CASE WHEN field_index = 'c147' AND multi_value_index IS NULL THEN field_value END) AS "ep_balance",
  max(CASE WHEN field_index = 'c146' AND multi_value_index IS NULL THEN field_value END) AS "er_balance",
  max(CASE WHEN field_index = 'c145' AND multi_value_index IS NULL THEN field_value END) AS "er_value_date",
  max(CASE WHEN field_index = 'c190' AND multi_value_index IS NULL THEN field_value END) AS "event",
  max(CASE WHEN field_index = 'c169' AND multi_value_index IS NULL THEN field_value END) AS "exposure_dates",
  max(CASE WHEN field_index = 'c209' AND multi_value_index IS NULL THEN field_value END) AS "external_posting",
  max(CASE WHEN field_index = 'c173' AND multi_value_index IS NULL THEN field_value END) AS "first_af_date",
  max(CASE WHEN field_index = 'c156' AND multi_value_index IS NULL THEN field_value END) AS "forward_mvmts",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 15 THEN field_value END) AS "ft_ref_nab",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 5 THEN field_value END) AS "hold_date",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 8 THEN field_value END) AS "hold_details",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 10 THEN field_value END) AS "hold_reason",
  max(CASE WHEN field_index = 'c135' AND multi_value_index IS NULL THEN field_value END) AS "ica_add_remove",
  max(CASE WHEN field_index = 'c136' AND multi_value_index IS NULL THEN field_value END) AS "ica_back_value",
  max(CASE WHEN field_index = 'c137' AND multi_value_index IS NULL THEN field_value END) AS "ica_main_acct",
  max(CASE WHEN field_index = 'c138' AND multi_value_index IS NULL THEN field_value END) AS "ica_main_date",
  max(CASE WHEN field_index = 'c132' AND multi_value_index IS NULL THEN field_value END) AS "ica_main_ratio",
  max(CASE WHEN field_index = 'c22' AND multi_value_index IS NULL THEN field_value END) AS "inactiv_marker",
  max(CASE WHEN field_index = 'c75' AND multi_value_index IS NULL THEN field_value END) AS "int_liq_ccy",
  max(CASE WHEN field_index = 'c96' AND multi_value_index IS NULL THEN field_value END) AS "interest_mkt",
  max(CASE WHEN field_index = 'c107' AND multi_value_index IS NULL THEN field_value END) AS "joint_notes",
  max(CASE WHEN field_index = 'c176' AND multi_value_index IS NULL THEN field_value END) AS "last_com_chg_date",
  max(CASE WHEN field_index = 'c10' AND multi_value_index IS NULL THEN field_value END) AS "limit_ref",
  max(CASE WHEN field_index = 'c89' AND multi_value_index IS NULL THEN field_value END) AS "link_to_limit",
  max(CASE WHEN field_index = 'c162' AND multi_value_index IS NULL THEN field_value END) AS "lock_inc_this_mvmt",
  max(CASE WHEN field_index = 'c91' AND multi_value_index IS NULL THEN field_value END) AS "locked_with_limit",
  max(CASE WHEN field_index = 'c183' AND multi_value_index IS NULL THEN field_value END) AS "mandate_appl",
  max(CASE WHEN field_index = 'c185' AND multi_value_index IS NULL THEN field_value END) AS "mandate_record",
  max(CASE WHEN field_index = 'c184' AND multi_value_index IS NULL THEN field_value END) AS "mandate_reg",
  max(CASE WHEN field_index = 'c6' AND multi_value_index IS NULL THEN field_value END) AS "mnemonic",
  max(CASE WHEN field_index = 'c224' AND multi_value_index IS NULL THEN field_value END) AS "multi_currency_parent",
  max(CASE WHEN field_index = 'c199' AND multi_value_index IS NULL THEN field_value END) AS "mv_alert_res1",
  max(CASE WHEN field_index = 'c198' AND multi_value_index IS NULL THEN field_value END) AS "mv_alert_res2",
  max(CASE WHEN field_index = 'c197' AND multi_value_index IS NULL THEN field_value END) AS "mv_alert_res3",
  max(CASE WHEN field_index = 'c165' AND multi_value_index IS NULL THEN field_value END) AS "next_acct_cap",
  max(CASE WHEN field_index = 'c164' AND multi_value_index IS NULL THEN field_value END) AS "next_af_date",
  max(CASE WHEN field_index = 'c166' AND multi_value_index IS NULL THEN field_value END) AS "next_exp_date",
  max(CASE WHEN field_index = 'c168' AND multi_value_index IS NULL THEN field_value END) AS "next_stmt_date",
  max(CASE WHEN field_index = 'c23' AND multi_value_index IS NULL THEN field_value END) AS "open_actual_bal",
  max(CASE WHEN field_index = 'c175' AND multi_value_index IS NULL THEN field_value END) AS "open_asset_type",
  max(CASE WHEN field_index = 'c78' AND multi_value_index IS NULL THEN field_value END) AS "opening_date",
  max(CASE WHEN field_index = 'c120' AND multi_value_index IS NULL THEN field_value END) AS "original_acct",
  max(CASE WHEN field_index = 'c210' AND multi_value_index IS NULL THEN field_value END) AS "parent_bv_date",
  max(CASE WHEN field_index = 'c76' AND multi_value_index IS NULL THEN field_value END) AS "passbook",
  max(CASE WHEN field_index = 'c170' AND multi_value_index IS NULL THEN field_value END) AS "portfolio_no",
  max(CASE WHEN field_index = 'c7' AND multi_value_index IS NULL THEN field_value END) AS "position_type",
  max(CASE WHEN field_index = 'c13' AND multi_value_index IS NULL THEN field_value END) AS "posting_restrict",
  max(CASE WHEN field_index = 'c103' AND multi_value_index IS NULL THEN field_value END) AS "premium_freq",
  max(CASE WHEN field_index = 'c112' AND multi_value_index IS NULL THEN field_value END) AS "reco_tolerance",
  max(CASE WHEN field_index = 'c18' AND multi_value_index IS NULL THEN field_value END) AS "referal_code",
  max(CASE WHEN field_index = 'c200' AND multi_value_index IS NULL THEN field_value END) AS "request_id",
  max(CASE WHEN field_index = 'c234' AND multi_value_index IS NULL THEN field_value END) AS "reserved_12",
  max(CASE WHEN field_index = 'c233' AND multi_value_index IS NULL THEN field_value END) AS "reserved_13",
  max(CASE WHEN field_index = 'c232' AND multi_value_index IS NULL THEN field_value END) AS "reserved_14",
  max(CASE WHEN field_index = 'c230' AND multi_value_index IS NULL THEN field_value END) AS "reserved_16",
  max(CASE WHEN field_index = 'c229' AND multi_value_index IS NULL THEN field_value END) AS "reserved_17",
  max(CASE WHEN field_index = 'c228' AND multi_value_index IS NULL THEN field_value END) AS "reserved_18",
  max(CASE WHEN field_index = 'c227' AND multi_value_index IS NULL THEN field_value END) AS "reserved_19",
  max(CASE WHEN field_index = 'c226' AND multi_value_index IS NULL THEN field_value END) AS "reserved_20",
  max(CASE WHEN field_index = 'c243' AND multi_value_index IS NULL THEN field_value END) AS "reserved_3",
  max(CASE WHEN field_index = 'c242' AND multi_value_index IS NULL THEN field_value END) AS "reserved_4",
  max(CASE WHEN field_index = 'c241' AND multi_value_index IS NULL THEN field_value END) AS "reserved_5",
  max(CASE WHEN field_index = 'c240' AND multi_value_index IS NULL THEN field_value END) AS "reserved_6",
  max(CASE WHEN field_index = 'c239' AND multi_value_index IS NULL THEN field_value END) AS "reserved_7",
  max(CASE WHEN field_index = 'c238' AND multi_value_index IS NULL THEN field_value END) AS "reserved_8",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 30 THEN field_value END) AS "revaluation",
  max(CASE WHEN field_index = 'c148' AND multi_value_index IS NULL THEN field_value END) AS "sb_group_id",
  max(CASE WHEN field_index = 'c212' AND multi_value_index IS NULL THEN field_value END) AS "secondary_limit_amt",
  max(CASE WHEN field_index = 'c116' AND multi_value_index IS NULL THEN field_value END) AS "serial_no_format",
  max(CASE WHEN field_index = 'c171' AND multi_value_index IS NULL THEN field_value END) AS "shadow_account",
  max(CASE WHEN field_index = 'c5' AND multi_value_index IS NULL THEN field_value END) AS "short_title",
  max(CASE WHEN field_index = 'c77' AND multi_value_index IS NULL THEN field_value END) AS "start_year_bal",
  max(CASE WHEN field_index = 'c33' AND multi_value_index IS NULL THEN field_value END) AS "tran_last_cr_auto",
  max(CASE WHEN field_index = 'c36' AND multi_value_index IS NULL THEN field_value END) AS "tran_last_cr_bank",
  max(CASE WHEN field_index = 'c30' AND multi_value_index IS NULL THEN field_value END) AS "tran_last_cr_cust",
  max(CASE WHEN field_index = 'c42' AND multi_value_index IS NULL THEN field_value END) AS "tran_last_dr_auto",
  max(CASE WHEN field_index = 'c45' AND multi_value_index IS NULL THEN field_value END) AS "tran_last_dr_bank",
  max(CASE WHEN field_index = 'c39' AND multi_value_index IS NULL THEN field_value END) AS "tran_last_dr_cust",
  max(CASE WHEN field_index = 'c193' AND multi_value_index IS NULL THEN field_value END) AS "value",
  max(CASE WHEN field_index = 'c79' AND multi_value_index IS NULL THEN field_value END) AS "value_date",
  max(CASE WHEN field_index = 'c19' AND multi_value_index IS NULL THEN field_value END) AS "waive_ledger_fee",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 33 THEN field_value END) AS "welcome_pack",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 34 THEN field_value END) AS "account_purpose",
  max(CASE WHEN field_index = 'c4' AND multi_value_index IS NULL THEN field_value END) AS "account_title_2",
  max(CASE WHEN field_index = 'c223' AND multi_value_index IS NULL THEN field_value END) AS "account_type",
  max(CASE WHEN field_index = 'c55' AND multi_value_index IS NULL THEN field_value END) AS "accr_chg_susp",
  max(CASE WHEN field_index = 'c62' AND multi_value_index IS NULL THEN field_value END) AS "accr_cr2_amount",
  max(CASE WHEN field_index = 'c63' AND multi_value_index IS NULL THEN field_value END) AS "accr_cr2_susp",
  max(CASE WHEN field_index = 'c61' AND multi_value_index IS NULL THEN field_value END) AS "accr_cr2_trans",
  max(CASE WHEN field_index = 'c58' AND multi_value_index IS NULL THEN field_value END) AS "accr_cr_amount",
  max(CASE WHEN field_index = 'c56' AND multi_value_index IS NULL THEN field_value END) AS "accr_cr_categ",
  max(CASE WHEN field_index = 'c59' AND multi_value_index IS NULL THEN field_value END) AS "accr_cr_susp",
  max(CASE WHEN field_index = 'c69' AND multi_value_index IS NULL THEN field_value END) AS "accr_dr2_trans",
  max(CASE WHEN field_index = 'c64' AND multi_value_index IS NULL THEN field_value END) AS "accr_dr_categ",
  max(CASE WHEN field_index = 'c67' AND multi_value_index IS NULL THEN field_value END) AS "accr_dr_susp",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 22 THEN field_value END) AS "accroual_amount",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 1 THEN field_value END) AS "activyty",
  max(CASE WHEN field_index = 'c144' AND multi_value_index IS NULL THEN field_value END) AS "all_in_one_product",
  max(CASE WHEN field_index = 'c211' AND multi_value_index IS NULL THEN field_value END) AS "allowed_bv_date",
  max(CASE WHEN field_index = 'c32' AND multi_value_index IS NULL THEN field_value END) AS "amnt_last_cr_auto",
  max(CASE WHEN field_index = 'c35' AND multi_value_index IS NULL THEN field_value END) AS "amnt_last_cr_bank",
  max(CASE WHEN field_index = 'c38' AND multi_value_index IS NULL THEN field_value END) AS "amnt_last_dr_cust",
  max(CASE WHEN field_index = 'c104' AND multi_value_index IS NULL THEN field_value END) AS "apr",
  max(CASE WHEN field_index = 'c181' AND multi_value_index IS NULL THEN field_value END) AS "arrangement_id",
  max(CASE WHEN field_index = 'c255' AND multi_value_index IS NULL THEN field_value END) AS "audit_date_time",
  max(CASE WHEN field_index = 'c254' AND multi_value_index IS NULL THEN field_value END) AS "auditor_code",
  max(CASE WHEN field_index = 'c251' AND multi_value_index IS NULL THEN field_value END) AS "authoriser",
  max(CASE WHEN field_index = 'c117' AND multi_value_index IS NULL THEN field_value END) AS "auto_pay_acct",
  max(CASE WHEN field_index = 'c119' AND multi_value_index IS NULL THEN field_value END) AS "auto_rec_ccy",
  max(CASE WHEN field_index = 'c153' AND multi_value_index IS NULL THEN field_value END) AS "av_auth_cr_mvmt",
  max(CASE WHEN field_index = 'c154' AND multi_value_index IS NULL THEN field_value END) AS "av_nau_cr_mvmt",
  max(CASE WHEN field_index = 'c155' AND multi_value_index IS NULL THEN field_value END) AS "available_bal",
  max(CASE WHEN field_index = 'c150' AND multi_value_index IS NULL THEN field_value END) AS "available_date",
  max(CASE WHEN field_index = 'c215' AND multi_value_index IS NULL THEN field_value END) AS "balance_conversion_mkt",
  max(CASE WHEN field_index = 'c51' AND multi_value_index IS NULL THEN field_value END) AS "cap_back_value",
  max(CASE WHEN field_index = 'c48' AND multi_value_index IS NULL THEN field_value END) AS "cap_date_c2_int",
  max(CASE WHEN field_index = 'c50' AND multi_value_index IS NULL THEN field_value END) AS "cap_date_d2_int",
  max(CASE WHEN field_index = 'c49' AND multi_value_index IS NULL THEN field_value END) AS "cap_date_dr_int",
  max(CASE WHEN field_index = 'c174' AND multi_value_index IS NULL THEN field_value END) AS "cash_pool_group",
  max(CASE WHEN field_index = 'c94' AND multi_value_index IS NULL THEN field_value END) AS "charge_mkt",
  max(CASE WHEN field_index = 'c252' AND multi_value_index IS NULL THEN field_value END) AS "co_code",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 31 THEN field_value END) AS "comp_code",
  max(CASE WHEN field_index = 'c98' AND multi_value_index IS NULL THEN field_value END) AS "con_interest_accr",
  max(CASE WHEN field_index = 'c21' AND multi_value_index IS NULL THEN field_value END) AS "condition_group",
  max(CASE WHEN field_index = 'c84' AND multi_value_index IS NULL THEN field_value END) AS "contingent_bal_dr",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 26 THEN field_value END) AS "cost_bonds",
  max(CASE WHEN field_index = 'c189' AND multi_value_index IS NULL THEN field_value END) AS "cr2_adj_amount",
  max(CASE WHEN field_index = 'c188' AND multi_value_index IS NULL THEN field_value END) AS "cr_adj_amount",
  max(CASE WHEN field_index = 'c214' AND multi_value_index IS NULL THEN field_value END) AS "credit_chk_condition",
  max(CASE WHEN field_index = 'c9' AND multi_value_index IS NULL THEN field_value END) AS "currency_market",
  max(CASE WHEN field_index = 'c1' AND multi_value_index IS NULL THEN field_value END) AS "customer",
  max(CASE WHEN field_index = 'c34' AND multi_value_index IS NULL THEN field_value END) AS "date_last_cr_bank",
  max(CASE WHEN field_index = 'c28' AND multi_value_index IS NULL THEN field_value END) AS "date_last_cr_cust",
  max(CASE WHEN field_index = 'c40' AND multi_value_index IS NULL THEN field_value END) AS "date_last_dr_auto",
  max(CASE WHEN field_index = 'c253' AND multi_value_index IS NULL THEN field_value END) AS "dept_code",
  max(CASE WHEN field_index = 'c221' AND multi_value_index IS NULL THEN field_value END) AS "emergency_reason",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 29 THEN field_value END) AS "eval_bal",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 6 THEN field_value END) AS "expiry_date",
  max(CASE WHEN field_index = 'c219' AND multi_value_index IS NULL THEN field_value END) AS "fa_status",
  max(CASE WHEN field_index = 'c191' AND multi_value_index IS NULL THEN field_value END) AS "field",
  max(CASE WHEN field_index = 'c121' AND multi_value_index IS NULL THEN field_value END) AS "from_date",
  max(CASE WHEN field_index = 'c172' AND multi_value_index IS NULL THEN field_value END) AS "fwd_entry_hold",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 7 THEN field_value END) AS "hold_amount",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 9 THEN field_value END) AS "hold_user",
  max(CASE WHEN field_index = 'c141' AND multi_value_index IS NULL THEN field_value END) AS "hvt_flag",
  max(CASE WHEN field_index = 'c177' AND multi_value_index IS NULL THEN field_value END) AS "ic_charge_id",
  max(CASE WHEN field_index = 'c180' AND multi_value_index IS NULL THEN field_value END) AS "ic_lst_prod_cap",
  max(CASE WHEN field_index = 'c178' AND multi_value_index IS NULL THEN field_value END) AS "ic_next_cap_date",
  max(CASE WHEN field_index = 'c179' AND multi_value_index IS NULL THEN field_value END) AS "ic_product",
  max(CASE WHEN field_index = 'c128' AND multi_value_index IS NULL THEN field_value END) AS "ica_distrib_ratio",
  max(CASE WHEN field_index = 'c130' AND multi_value_index IS NULL THEN field_value END) AS "ica_distrib_type",
  max(CASE WHEN field_index = 'c127' AND multi_value_index IS NULL THEN field_value END) AS "ica_main_account",
  max(CASE WHEN field_index = 'c129' AND multi_value_index IS NULL THEN field_value END) AS "ica_main_acct_ind",
  max(CASE WHEN field_index = 'c133' AND multi_value_index IS NULL THEN field_value END) AS "ica_new_main_acc",
  max(CASE WHEN field_index = 'c131' AND multi_value_index IS NULL THEN field_value END) AS "ica_post_interest",
  max(CASE WHEN field_index = 'c134' AND multi_value_index IS NULL THEN field_value END) AS "ica_start_date",
  max(CASE WHEN field_index = 'c249' AND multi_value_index IS NULL THEN field_value END) AS "inputter",
  max(CASE WHEN field_index = 'c74' AND multi_value_index IS NULL THEN field_value END) AS "int_liqu_acct",
  max(CASE WHEN field_index = 'c73' AND multi_value_index IS NULL THEN field_value END) AS "int_liqu_type",
  max(CASE WHEN field_index = 'c17' AND multi_value_index IS NULL THEN field_value END) AS "int_no_booking",
  max(CASE WHEN field_index = 'c95' AND multi_value_index IS NULL THEN field_value END) AS "interest_ccy",
  max(CASE WHEN field_index = 'c16' AND multi_value_index IS NULL THEN field_value END) AS "interest_comp_acct",
  max(CASE WHEN field_index = 'c15' AND multi_value_index IS NULL THEN field_value END) AS "interest_liqu_acct",
  max(CASE WHEN field_index = 'c105' AND multi_value_index IS NULL THEN field_value END) AS "joint_holder",
  max(CASE WHEN field_index = 'c109' AND multi_value_index IS NULL THEN field_value END) AS "ledg_reco_with",
  max(CASE WHEN field_index = 'c216' AND multi_value_index IS NULL THEN field_value END) AS "limit_key",
  max(CASE WHEN field_index = 'c218' AND multi_value_index IS NULL THEN field_value END) AS "limit_proc_type",
  max(CASE WHEN field_index = 'c139' AND multi_value_index IS NULL THEN field_value END) AS "liquidation_mode",
  max(CASE WHEN field_index = 'c122' AND multi_value_index IS NULL THEN field_value END) AS "locked_amount",
  max(CASE WHEN field_index = 'c161' AND multi_value_index IS NULL THEN field_value END) AS "master_account",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 25 THEN field_value END) AS "matur_date",
  max(CASE WHEN field_index = 'c160' AND multi_value_index IS NULL THEN field_value END) AS "max_sub_account",
  max(CASE WHEN field_index = 'c208' AND multi_value_index IS NULL THEN field_value END) AS "multi_currency",
  max(CASE WHEN field_index = 'c196' AND multi_value_index IS NULL THEN field_value END) AS "mv_alert_res4",
  max(CASE WHEN field_index = 'c195' AND multi_value_index IS NULL THEN field_value END) AS "mv_alert_res5",
  max(CASE WHEN field_index = 'c194' AND multi_value_index IS NULL THEN field_value END) AS "mv_alert_res6",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 32 THEN field_value END) AS "nab_flag",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 24 THEN field_value END) AS "no_of_bonds",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 11 THEN field_value END) AS "old_account",
  max(CASE WHEN field_index = 'c25' AND multi_value_index IS NULL THEN field_value END) AS "online_actual_bal",
  max(CASE WHEN field_index = 'c26' AND multi_value_index IS NULL THEN field_value END) AS "online_cleared_bal",
  max(CASE WHEN field_index = 'c149' AND multi_value_index IS NULL THEN field_value END) AS "open_available_bal",
  max(CASE WHEN field_index = 'c85' AND multi_value_index IS NULL THEN field_value END) AS "open_category",
  max(CASE WHEN field_index = 'c24' AND multi_value_index IS NULL THEN field_value END) AS "open_cleared_bal",
  max(CASE WHEN field_index = 'c86' AND multi_value_index IS NULL THEN field_value END) AS "open_val_dated_bal",
  max(CASE WHEN field_index = 'c192' AND multi_value_index IS NULL THEN field_value END) AS "operand",
  max(CASE WHEN field_index = 'c118' AND multi_value_index IS NULL THEN field_value END) AS "orig_ccy_payment",
  max(CASE WHEN field_index = 'c12' AND multi_value_index IS NULL THEN field_value END) AS "other_officer",
  max(CASE WHEN field_index = 'c111' AND multi_value_index IS NULL THEN field_value END) AS "our_ext_acct_no",
  max(CASE WHEN field_index = 'c140' AND multi_value_index IS NULL THEN field_value END) AS "overdue_status",
  max(CASE WHEN field_index = 'c246' AND multi_value_index IS NULL THEN field_value END) AS "override",
  max(CASE WHEN field_index = 'c207' AND multi_value_index IS NULL THEN field_value END) AS "parent_account",
  max(CASE WHEN field_index = 'c113' AND multi_value_index IS NULL THEN field_value END) AS "pending_id",
  max(CASE WHEN field_index = 'c101' AND multi_value_index IS NULL THEN field_value END) AS "premium_type",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 27 THEN field_value END) AS "prev_bal",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 28 THEN field_value END) AS "price_eval",
  max(CASE WHEN field_index = 'c14' AND multi_value_index IS NULL THEN field_value END) AS "reconcile_acct",
  max(CASE WHEN field_index = 'c247' AND multi_value_index IS NULL THEN field_value END) AS "record_status",
  max(CASE WHEN field_index = 'c217' AND multi_value_index IS NULL THEN field_value END) AS "reducing_limit",
  max(CASE WHEN field_index = 'c202' AND multi_value_index IS NULL THEN field_value END) AS "ref_data_item",
  max(CASE WHEN field_index = 'c203' AND multi_value_index IS NULL THEN field_value END) AS "ref_data_value",
  max(CASE WHEN field_index = 'c106' AND multi_value_index IS NULL THEN field_value END) AS "relation_code",
  max(CASE WHEN field_index = 'c245' AND multi_value_index IS NULL THEN field_value END) AS "reserved_1",
  max(CASE WHEN field_index = 'c236' AND multi_value_index IS NULL THEN field_value END) AS "reserved_10",
  max(CASE WHEN field_index = 'c235' AND multi_value_index IS NULL THEN field_value END) AS "reserved_11",
  max(CASE WHEN field_index = 'c231' AND multi_value_index IS NULL THEN field_value END) AS "reserved_15",
  max(CASE WHEN field_index = 'c244' AND multi_value_index IS NULL THEN field_value END) AS "reserved_2",
  max(CASE WHEN field_index = 'c225' AND multi_value_index IS NULL THEN field_value END) AS "reserved_21",
  max(CASE WHEN field_index = 'c237' AND multi_value_index IS NULL THEN field_value END) AS "reserved_9",
  max(CASE WHEN field_index = 'c222' AND multi_value_index IS NULL THEN field_value END) AS "risk_stage",
  max(CASE WHEN field_index = 'c206' AND multi_value_index IS NULL THEN field_value END) AS "sam_id_hist",
  max(CASE WHEN field_index = 'c142' AND multi_value_index IS NULL THEN field_value END) AS "single_limit",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 13 THEN field_value END) AS "start_nab",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 16 THEN field_value END) AS "stmt_date",
  max(CASE WHEN field_index = 'c110' AND multi_value_index IS NULL THEN field_value END) AS "stmt_reco_with",
  max(CASE WHEN field_index = 'c115' AND multi_value_index IS NULL THEN field_value END) AS "stock_control_type",
  max(CASE WHEN field_index = 'c126' AND multi_value_index IS NULL THEN field_value END) AS "tax_at_settle",
  max(CASE WHEN field_index = 'c125' AND multi_value_index IS NULL THEN field_value END) AS "tax_suspend",
  max(CASE WHEN field_index = 'c114' AND multi_value_index IS NULL THEN field_value END) AS "total_pending",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 21 THEN field_value END) AS "under_age_interest_date",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 20 THEN field_value END) AS "under_age_no_of_months",
  max(CASE WHEN field_index = 'c82' AND multi_value_index IS NULL THEN field_value END) AS "value_dated_bal",
  max(CASE WHEN field_index = 'c20' AND multi_value_index = 2 THEN field_value END) AS "version_name",
  max(CASE WHEN field_index = 'c27' AND multi_value_index IS NULL THEN field_value END) AS "working_balance",
  max(ingested_at) AS ingested_at
FROM iceberg.bronze.account_xml_attributes
GROUP BY recid;

SELECT count(*) AS account_wide_count
FROM iceberg.bronze.account_wide;
