
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: pyspark-simple-job-airflow
  namespace: spark-operator-v2
spec:
  restartPolicy:
    type: Never
  mode: cluster
  deps: {}
  driver:
    cores: 1
    labels:
      version: 3.5.5
    memory: 512m
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsGroup: 185
      runAsNonRoot: true
      runAsUser: 185
    serviceAccount: spark-operator-spark
    volumeMounts:
      - mountPath: /app
        name: python-script
  imagePullPolicy: IfNotPresent
  executor:
    cores: 1
    instances: 1
    labels:
      version: 3.5.5
    memory: 512m
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsGroup: 185
      runAsNonRoot: true
      runAsUser: 185
  mainApplicationFile: 'local:///app/simple_job.py'
  volumes:
    - configMap:
        defaultMode: 493
        name: pyspark-simple-job
      name: python-script
  type: Python
  image: 'scb-quay-quay-enterprise.apps.ocp-hub.scb.local/scbhq/spark:including-jars'
