-- Generated by gen_sql.py --mode ingest --table account
-- Oracle is read-only. XMLTYPE is not natively mapped by the Trino Oracle
-- connector, so the value is serialized with getClobVal() inside a native
-- passthrough. This is the ONLY place getClobVal() appears -- everything
-- downstream reads Iceberg.

CREATE SCHEMA IF NOT EXISTS iceberg.bronze
WITH (location = 's3://warehouse/bronze');

DROP TABLE IF EXISTS iceberg.bronze.account_raw;

CREATE TABLE iceberg.bronze.account_raw
WITH (format = 'PARQUET') AS
SELECT
  recid,
  xmlrecord,
  current_timestamp AS ingested_at
FROM TABLE(
  oracle.system.query(
    query => 'SELECT
      a.recid,
      a.xmlrecord.getClobVal() AS xmlrecord
    FROM source_user.account a'
  )
);

-- Truncation check: compare against Oracle's own length for the largest doc.
--   Oracle: SELECT recid, dbms_lob.getlength(xmlrecord.getclobval())
--           FROM source_user.account ORDER BY 2 DESC FETCH FIRST 5 ROWS ONLY;
SELECT recid, length(xmlrecord) AS xml_length
FROM iceberg.bronze.account_raw
ORDER BY xml_length DESC
LIMIT 5;

-- Token completeness: these two counts must match once self-closing tags are
-- normalized (Oracle's XMLTYPE serializer renders empty elements as
-- self-closing, e.g. <c100/>, regardless of how they were written -- confirmed
-- against a live round-trip, not a hypothetical). If they still don't match,
-- the tag regex is missing some other element shape.
SELECT
  count(*) AS records,
  sum(cardinality(regexp_extract_all(
    regexp_replace(xmlrecord, '<(c\d+)([^>]*)/>', '<$1$2></$1>'),
    '<(c\d+)([^>]*)>([^<]*)</c\d+>', 1
  ))) AS matched_tags,
  sum(cardinality(regexp_extract_all(xmlrecord, '<c\d+[ />]'))) AS raw_tag_opens
FROM iceberg.bronze.account_raw;
