-- Generated by gen_sql.py --mode ingest --table account
-- XMLTYPE is unsupported by the Trino Oracle connector; getClobVal()
-- serializes it via native passthrough. Only usage in the pipeline --
-- everything downstream reads Iceberg.

CREATE SCHEMA IF NOT EXISTS iceberg.bronze
WITH (location = 's3://warehouse/bronze');

DROP TABLE IF EXISTS iceberg.bronze.account_raw;

CREATE TABLE iceberg.bronze.account_raw
WITH (format = 'PARQUET') AS
SELECT
  recid,
  xmlrecord,
  current_timestamp AS ingested_at
FROM TABLE(
  oracle.system.query(
    query => 'SELECT
      a.recid,
      a.xmlrecord.getClobVal() AS xmlrecord
    FROM source_user.account a'
  )
);

-- Truncation check: Iceberg length vs Oracle dbms_lob.getlength().
-- Zero rows = no truncation; any row returned needs investigation.
WITH iceberg_lengths AS (
  SELECT recid, length(xmlrecord) AS iceberg_length
  FROM iceberg.bronze.account_raw
),
oracle_lengths AS (
  SELECT recid, oracle_length
  FROM TABLE(
    oracle.system.query(
      query => 'SELECT a.recid, CAST(dbms_lob.getlength(a.xmlrecord.getclobval()) AS NUMBER(10)) AS oracle_length
      FROM source_user.account a'
    )
  )
)
SELECT i.recid, i.iceberg_length, o.oracle_length
FROM iceberg_lengths i
JOIN oracle_lengths o ON i.recid = o.recid
WHERE i.iceberg_length <> o.oracle_length;

-- Token completeness: matched_tags vs raw_tag_opens must be equal after
-- normalizing self-closing tags. A mismatch means the regex is missing
-- an element shape.
SELECT
  count(*) AS records,
  sum(cardinality(regexp_extract_all(
    regexp_replace(xmlrecord, '<(c\d+)([^>]*)/>', '<$1$2></$1>'),
    '<(c\d+)([^>]*)>([^<]*)</c\d+>', 1
  ))) AS matched_tags,
  sum(cardinality(regexp_extract_all(xmlrecord, '<c\d+[ />]'))) AS raw_tag_opens
FROM iceberg.bronze.account_raw;
