-- Generated by gen_sql.py --mode ingest-refresh --table account
-- Re-reads all of Oracle and merges by recid. Oracle stays read-only; the
-- target is what becomes incremental. Deletes are intentionally not inferred --
-- that needs a source tombstone/CDC feed.

DROP TABLE IF EXISTS iceberg.bronze.account_raw_stage;

CREATE TABLE iceberg.bronze.account_raw_stage
WITH (format = 'PARQUET') AS
SELECT
  recid,
  xmlrecord,
  current_timestamp AS ingested_at
FROM TABLE(
  oracle.system.query(
    query => 'SELECT
      a.recid,
      a.xmlrecord.getClobVal() AS xmlrecord
    FROM source_user.account a'
  )
);

MERGE INTO iceberg.bronze.account_raw AS t
USING iceberg.bronze.account_raw_stage AS s
ON t.recid = s.recid
WHEN MATCHED AND t.xmlrecord IS DISTINCT FROM s.xmlrecord THEN UPDATE SET
  xmlrecord = s.xmlrecord,
  ingested_at = s.ingested_at
WHEN NOT MATCHED THEN INSERT (recid, xmlrecord, ingested_at)
VALUES (s.recid, s.xmlrecord, s.ingested_at);

DROP TABLE IF EXISTS iceberg.bronze.account_raw_stage;
