-- Generated by gen_sql.py --mode incremental --table account
-- Window: only re-tokenizes iceberg.bronze.account_raw rows whose ingested_at falls in [20260831, 20260831]. ingest-refresh only bumps ingested_at when content actually changed, so this must use the same window (or wider) as the ingest-refresh that fed this run, or a real change outside it would be silently skipped here.
-- Prerequisite: run --mode bootstrap once, and --mode ingest-refresh before this.

DROP TABLE IF EXISTS iceberg.bronze.account_attributes_stage;

CREATE TABLE iceberg.bronze.account_attributes_stage
WITH (format = 'PARQUET') AS
-- Part 1/4 -- read XML, hash it, normalize self-closing empty tags.
WITH raw AS (
  SELECT
    recid,
    xmlrecord,
    to_hex(md5(to_utf8(xmlrecord))) AS xml_hash,
    regexp_replace(xmlrecord, '<(c\d+)([^>]*)/>', '<$1$2></$1>') AS xmlrecord_norm
  FROM (SELECT * FROM iceberg.bronze.account_raw WHERE ingested_at >= date_parse('20260831', '%Y%m%d') AND ingested_at < date_parse('20260831', '%Y%m%d') + INTERVAL '1' DAY) AS windowed_raw
),

-- Part 2/4 -- extract every tag into one (tag, m, s, value) struct per
-- occurrence, one array per record. 3 scans total, not one per field.
tokens AS (
  SELECT
    recid,
    xml_hash,
    transform(
      zip(
        regexp_extract_all(xmlrecord_norm, '<(c\d+)([^>]*)>([^<]*)</c\d+>', 1),
        regexp_extract_all(xmlrecord_norm, '<(c\d+)([^>]*)>([^<]*)</c\d+>', 2),
        regexp_extract_all(xmlrecord_norm, '<(c\d+)([^>]*)>([^<]*)</c\d+>', 3)
      ),
      e -> CAST(
        ROW(
          e[1],
          CAST(COALESCE(regexp_extract(e[2], 'm="(\d+)"', 1), '1') AS INTEGER),
          CAST(COALESCE(regexp_extract(e[2], 's="(\d+)"', 1), '1') AS INTEGER),
          CASE WHEN e[3] = '' THEN NULL ELSE replace(replace(replace(replace(replace(replace(e[3], '&lt;', '<'), '&gt;', '>'), '&quot;', '"'), '&apos;', ''''), '&#39;', ''''), '&amp;', '&') END
        ) AS ROW(tag VARCHAR, m INTEGER, s INTEGER, val VARCHAR)
      )
    ) AS entries
  FROM raw
),

-- Part 3/4 -- one row per tag occurrence. Sentinel keeps a no-tag record's
-- recid alive (UNNEST on an empty array drops the row); filtered out below.
exploded AS (
  SELECT t.recid, t.xml_hash, u.tag, u.m, u.s, u.val
  FROM tokens t
  CROSS JOIN UNNEST(
    IF(cardinality(t.entries) = 0,
       ARRAY[CAST(ROW('__empty__', 1, 1, NULL) AS ROW(tag VARCHAR, m INTEGER, s INTEGER, val VARCHAR))],
       t.entries)
  ) AS u(tag, m, s, val)
)
SELECT
  recid,
  tag AS field_index,
  m AS m_index,
  s AS s_index,
  val AS field_value,
  xml_hash,
  current_timestamp AS ingested_at
FROM exploded
WHERE tag != '__empty__';

DROP TABLE IF EXISTS iceberg.bronze.account_attributes_changed;

CREATE TABLE iceberg.bronze.account_attributes_changed
WITH (format = 'PARQUET') AS
SELECT DISTINCT s.recid
FROM iceberg.bronze.account_attributes_stage AS s
LEFT JOIN (SELECT DISTINCT recid, xml_hash FROM iceberg.bronze.account_attributes) AS t
  ON t.recid = s.recid
WHERE t.recid IS NULL OR t.xml_hash IS DISTINCT FROM s.xml_hash;

DELETE FROM iceberg.bronze.account_attributes
WHERE recid IN (SELECT recid FROM iceberg.bronze.account_attributes_changed);

INSERT INTO iceberg.bronze.account_attributes
SELECT s.*
FROM iceberg.bronze.account_attributes_stage AS s
JOIN iceberg.bronze.account_attributes_changed AS c ON c.recid = s.recid;

SELECT count(*) AS changed_records FROM iceberg.bronze.account_attributes_changed;

DROP TABLE IF EXISTS iceberg.bronze.account_attributes_stage;
DROP TABLE IF EXISTS iceberg.bronze.account_attributes_changed;
