-- Generated by gen_sql.py --mode reconcile --table account
-- With EAV output there is no schema to ALTER -- new fields already land as
-- new field_index values (see --mode bootstrap). This instead reports the
-- other direction: tags present in real data with no lookup row naming them.

SELECT DISTINCT a.field_index
FROM iceberg.bronze.account_attributes AS a
LEFT JOIN iceberg.bronze.lookup_metadata AS l
  ON l.table_name = 'account' AND l.field_index = a.field_index
WHERE l.field_index IS NULL
ORDER BY a.field_index;
